### PR TITLE
Add author metadata

### PR DESCRIPTION
**Pull request by CameronHamidi**
author_dict in Posts endpoint now returns author's id, name, avatar url, biography, Sun profile link, twitter link, linkedin link, and email address

### CODE REVIEW

**Comment by steamingcow** [comment]
Why do we need to set everything with the empty string to null?

**Comment by CameronHamidi** [comment]
> 
> 
> Why do we need to set everything with the empty string to null?

Requested by Austin so that the iOS team can work with optionals.

**Comment by steamingcow** [comment]
Is is possible to factor that out into a helper function so the code is more concise? I think you could just wrap every element of author_dict in a helper function, or create a general helper function which goes through an array and if any element is the empty string then set it to null instead. What do you think?

**Comment by CameronHamidi** [comment]
> Is is possible to factor that out into a helper function so the code is more concise? I think you could just wrap every element of author_dict in a helper function, or create a general helper function which goes through an array and if any element is the empty string then set it to null instead. What do you think?

Yeah that's a good idea; the new commit does that and makes the code a bit neater.

**Comment by steamingcow** [comment]
Can we do the same for the other block of code that manually sets things to null? Is it different?

**Pull request merged**
